version: "3.8"

services:
  app:
    build: .
    image: basicllmchatbot:latest
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
    env_file:
      - core/.env
    volumes:
      - ./core/PDF:/app/core/PDF:ro
